name: Build and Test

permissions:
  contents: write
  packages: write
  pages: write

on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore: ['docs/**', '*.md']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'
        cache-dependency-path: 'go.sum'

    - name: Build
      run: go build ./cmd/etcd_fdw

    - name: GolangCI-Lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest      

    - name: Run tests
      run: go test -v -race -coverprofile=coverage.out ./...

    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        file: coverage.out 
